### ISSUE TITLE
Feature Request: Configure site default for visibility and order

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-dashboard#46]
Right now, each user can configure the order and visibility of their own tiles. However, it would be nice if a site admin could configure the defaults of what tiles are visible and in what order. Obviously a user's preferences would override this, but it would set the initial state for new users based on the context of the site.

**Comment by corsacca** [comment]
@cairocoder01 this is already implement in the WP Admin > Extensions (D.T) > Dashboard
![image](https://github.com/DiscipleTools/disciple-tools-dashboard/assets/24901539/6daf4203-3e11-442a-8c2b-d52fdac04370)

**Comment by cairocoder01** [comment]
Oops! My bad. I never even checked. That is exactly what I wanted. Thanks.

**Comment by corsacca** [comment]
@cairocoder01 :D No worries. I had forgotten about it tool until last week. 
I wonder if we would benefit from a link to the WP admin shown to admins on the ordering tile.
