### ISSUE TITLE
Modifying a Field...?

### ISSUE THREAD

**Issue by soulascribe** [DiscipleTools/disciple-tools-dashboard#5]
I'm having a real challenge figuring out how to change / modify a field once I've created a custom one. It gives me the option to create a "Drop down", but I never get a place to fill out the custom answers. In my case, I'm making a progress drop-down to indicate which section of our training course the learner has completed (e.g. Section 1, Section 2, etc...) Here's the screen capture / video: https://youtu.be/YNBfJE-3VEc

**Comment by corsacca** [comment]
This question has been asked here: https://github.com/DiscipleTools/disciple-tools-webform/issues/51
